export const chats = [
  {
    id: 1,
    profileName: 'Анна',
    avatar: '',
    sentTime: '12:30',
    messageText: 'Привет, как дела?',
    messageCount: 3,
    isActive: false,
  },
  {
    id: 2,
    profileName: 'Иван',
    avatar: '',
    sentTime: '10:15',
    messageText: 'Документы готовы',
    messageCount: 0,
    isActive: true,
  },
  {
    id: 1,
    profileName: 'Анна',
    avatar: '',
    sentTime: '12:30',
    messageText: 'Привет, как дела?',
    messageCount: 3,
    isActive: false,
  },
  {
    id: 2,
    profileName: 'Иван',
    avatar: '',
    sentTime: '10:15',
    messageText: 'Документы готовы',
    messageCount: 0,
    isActive: true,
  },
  {
    id: 1,
    profileName: 'Анна',
    avatar: '',
    sentTime: '12:30',
    messageText: 'Привет, как дела?',
    messageCount: 3,
    isActive: false,
  },
  {
    id: 2,
    profileName: 'Иван',
    avatar: '',
    sentTime: '10:15',
    messageText: 'Документы готовы',
    messageCount: 0,
    isActive: true,
  },
  {
    id: 1,
    profileName: 'Анна',
    avatar: '',
    sentTime: '12:30',
    messageText: 'Привет, как дела?',
    messageCount: 3,
    isActive: false,
  },
  {
    id: 2,
    profileName: 'Иван',
    avatar: '',
    sentTime: '10:15',
    messageText: 'Документы готовы',
    messageCount: 0,
    isActive: true,
  },
  {
    id: 1,
    profileName: 'Анна',
    avatar: '',
    sentTime: '12:30',
    messageText: 'Привет, как дела?',
    messageCount: 3,
    isActive: false,
  },
  {
    id: 2,
    profileName: 'Иван',
    avatar: '',
    sentTime: '10:15',
    messageText: 'Документы готовы',
    messageCount: 0,
    isActive: true,
  },
  {
    id: 1,
    profileName: 'Анна',
    avatar: '',
    sentTime: '12:30',
    messageText: 'Привет, как дела?',
    messageCount: 3,
    isActive: false,
  },
  {
    id: 2,
    profileName: 'Иван',
    avatar: '',
    sentTime: '10:15',
    messageText: 'Документы готовы',
    messageCount: 0,
    isActive: true,
  },
  {
    id: 1,
    profileName: 'Анна',
    avatar: '',
    sentTime: '12:30',
    messageText: 'Привет, как дела?',
    messageCount: 3,
    isActive: false,
  },
  {
    id: 2,
    profileName: 'Иван',
    avatar: '',
    sentTime: '10:15',
    messageText: 'Документы готовы',
    messageCount: 0,
    isActive: true,
  },
  {
    id: 1,
    profileName: 'Анна',
    avatar: '',
    sentTime: '12:30',
    messageText: 'Привет, как дела?',
    messageCount: 3,
    isActive: false,
  },
  {
    id: 2,
    profileName: 'Иван',
    avatar: '',
    sentTime: '10:15',
    messageText: 'Документы готовы',
    messageCount: 0,
    isActive: true,
  },
  {
    id: 1,
    profileName: 'Анна',
    avatar: '',
    sentTime: '12:30',
    messageText: 'Привет, как дела?',
    messageCount: 3,
    isActive: false,
  },
  {
    id: 2,
    profileName: 'Иван',
    avatar: '',
    sentTime: '10:15',
    messageText: 'Документы готовы',
    messageCount: 0,
    isActive: true,
  },
  {
    id: 1,
    profileName: 'Анна',
    avatar: '',
    sentTime: '12:30',
    messageText: 'Привет, как дела?',
    messageCount: 3,
    isActive: false,
  },
  {
    id: 2,
    profileName: 'Иван',
    avatar: '',
    sentTime: '10:15',
    messageText: 'Документы готовы',
    messageCount: 0,
    isActive: true,
  },
  {
    id: 1,
    profileName: 'Анна',
    avatar: '',
    sentTime: '12:30',
    messageText: 'Привет, как дела?',
    messageCount: 3,
    isActive: false,
  },
  {
    id: 2,
    profileName: 'Иван',
    avatar: '',
    sentTime: '10:15',
    messageText: 'Документы готовы',
    messageCount: 0,
    isActive: true,
  },
  {
    id: 1,
    profileName: 'Анна',
    avatar: '',
    sentTime: '12:30',
    messageText: 'Привет, как дела?',
    messageCount: 3,
    isActive: false,
  },
  {
    id: 2,
    profileName: 'Иван',
    avatar: '',
    sentTime: '10:15',
    messageText: 'Документы готовы',
    messageCount: 0,
    isActive: true,
  },
  {
    id: 1,
    profileName: 'Анна',
    avatar: '',
    sentTime: '12:30',
    messageText: 'Привет, как дела?',
    messageCount: 3,
    isActive: false,
  },
  {
    id: 2,
    profileName: 'Иван',
    avatar: '',
    sentTime: '10:15',
    messageText: 'Документы готовы',
    messageCount: 0,
    isActive: true,
  },
  {
    id: 1,
    profileName: 'Анна',
    avatar: '',
    sentTime: '12:30',
    messageText: 'Привет, как дела?',
    messageCount: 3,
    isActive: false,
  },
  {
    id: 2,
    profileName: 'Иван',
    avatar: '',
    sentTime: '10:15',
    messageText: 'Документы готовы',
    messageCount: 0,
    isActive: true,
  },
  {
    id: 1,
    profileName: 'Анна',
    avatar: '',
    sentTime: '12:30',
    messageText: 'Привет, как дела?',
    messageCount: 3,
    isActive: false,
  },
  {
    id: 2,
    profileName: 'Иван',
    avatar: '',
    sentTime: '10:15',
    messageText: 'Документы готовы',
    messageCount: 0,
    isActive: true,
  },
  {
    id: 1,
    profileName: 'Анна',
    avatar: '',
    sentTime: '12:30',
    messageText: 'Привет, как дела?',
    messageCount: 3,
    isActive: false,
  },
  {
    id: 2,
    profileName: 'Иван',
    avatar: '',
    sentTime: '10:15',
    messageText: 'Документы готовы',
    messageCount: 0,
    isActive: true,
  },
  {
    id: 1,
    profileName: 'Анна',
    avatar: '',
    sentTime: '12:30',
    messageText: 'Привет, как дела?',
    messageCount: 3,
    isActive: false,
  },
  {
    id: 2,
    profileName: 'Иван',
    avatar: '',
    sentTime: '10:15',
    messageText: 'Документы готовы',
    messageCount: 0,
    isActive: true,
  },
  {
    id: 1,
    profileName: 'Анна',
    avatar: '',
    sentTime: '12:30',
    messageText: 'Привет, как дела?',
    messageCount: 3,
    isActive: false,
  },
  {
    id: 2,
    profileName: 'Иван',
    avatar: '',
    sentTime: '10:15',
    messageText: 'Документы готовы',
    messageCount: 0,
    isActive: true,
  },
  {
    id: 1,
    profileName: 'Анна',
    avatar: '',
    sentTime: '12:30',
    messageText: 'Привет, как дела?',
    messageCount: 3,
    isActive: false,
  },
  {
    id: 2,
    profileName: 'Иван',
    avatar: '',
    sentTime: '10:15',
    messageText: 'Документы готовы',
    messageCount: 0,
    isActive: true,
  },
  {
    id: 1,
    profileName: 'Анна',
    avatar: '',
    sentTime: '12:30',
    messageText: 'Привет, как дела?',
    messageCount: 3,
    isActive: false,
  },
  {
    id: 2,
    profileName: 'Иван',
    avatar: '',
    sentTime: '10:15',
    messageText: 'Документы готовы',
    messageCount: 0,
    isActive: true,
  },
  {
    id: 1,
    profileName: 'Анна',
    avatar: '',
    sentTime: '12:30',
    messageText: 'Привет, как дела?',
    messageCount: 3,
    isActive: false,
  },
  {
    id: 2,
    profileName: 'Иван',
    avatar: '',
    sentTime: '10:15',
    messageText: 'Документы готовы',
    messageCount: 0,
    isActive: true,
  },
  {
    id: 1,
    profileName: 'Анна',
    avatar: '',
    sentTime: '12:30',
    messageText: 'Привет, как дела?',
    messageCount: 3,
    isActive: false,
  },
  {
    id: 2,
    profileName: 'Иван',
    avatar: '',
    sentTime: '10:15',
    messageText: 'Документы готовы',
    messageCount: 0,
    isActive: true,
  },
  {
    id: 1,
    profileName: 'Анна',
    avatar: '',
    sentTime: '12:30',
    messageText: 'Привет, как дела?',
    messageCount: 3,
    isActive: false,
  },
  {
    id: 2,
    profileName: 'Иван',
    avatar: '',
    sentTime: '10:15',
    messageText: 'Документы готовы',
    messageCount: 0,
    isActive: true,
  },
  {
    id: 1,
    profileName: 'Анна',
    avatar: '',
    sentTime: '12:30',
    messageText: 'Привет, как дела?',
    messageCount: 3,
    isActive: false,
  },
  {
    id: 2,
    profileName: 'Иван',
    avatar: '',
    sentTime: '10:15',
    messageText: 'Документы готовы',
    messageCount: 0,
    isActive: true,
  },
  {
    id: 1,
    profileName: 'Анна',
    avatar: '',
    sentTime: '12:30',
    messageText: 'Привет, как дела?',
    messageCount: 3,
    isActive: false,
  },
  {
    id: 2,
    profileName: 'Иван',
    avatar: '',
    sentTime: '10:15',
    messageText: 'Документы готовы',
    messageCount: 0,
    isActive: true,
  },
];
